version: '3'
services:

 postgres:
  image: postgres
  volumes:
   - postgres:/var/lib/postgresql/data
  environment:
   POSTGRES_DB: keycloak
   POSTGRES_USER: keycloak
   POSTGRES_PASSWORD: password

 keycloak:
  image: quay.io/keycloak/keycloak:11.0.1
  environment:
   DB_VENDOR: POSTGRES
   DB_ADDR: postgres
   DB_DATABASE: keycloak
   DB_USER: keycloak
   DB_SCHEMA: public
   DB_PASSWORD: password
   KEYCLOAK_USER: admin
   KEYCLOAK_PASSWORD: Pa55w0rd
  ports:
   - 8080:8080
  depends_on:
   - postgres

 strapi:
  build:
   context: .
  image: strapi/strapi:3.1-alpine-keycloak
  depends_on:
   - postgres
   - keycloak
  ports:
   - 1337:1337

volumes:
 postgres:  
